apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: st-petersburg-pool
spec:
  cidr: 192.168.100.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: location == 'st-petersburg'

---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: moscow-pool
spec:
  cidr: 192.168.200.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: location == 'moscow'
